[theme]
primaryColor = "#667eea"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#2c3e50"
font = "sans serif"

[server]
maxUploadSize = 200

[browser]
gatherUsageStats = false